---
abstract: 'Categorize weighted hashes using a Domain Specific Language'
author:
  - 'Philippe Bruhat (BooK) <book@cpan.org>'
build_requires:
  File::Find: 0
  Test::More: 0.88
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Hash-Weighted-Categorize
requires:
  Moo: 0
  strict: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Hash-Weighted-Categorize
  repository: http://github.com/book/Hash-Weighted-Categorize.git
version: 0.002
